### ISSUE TITLE
Validator should allow unknown extensions

### ISSUE THREAD

**Issue by gotdan** [inferno-framework/bulk-data-test-kit#22]
As discussed in https://github.com/synthetichealth/synthea/issues/1437 and https://chat.fhir.org/#narrow/stream/291844-FHIR-Validator/topic/Extension.20could.20not.20be.20found/near/435291152 , valid Synthea resources are failing the step "2.2.2.03 All resources returned are valid FHIR resources" since they contain extensions that are defined outside of US Core. Validation in Inferno should probably allow resources to contain any extensions, but another option would be to have a configuration option for the user to pass in a list of allowed extensions in their dataset.

**Comment by dehall** [comment]
Are you using the hosted instance of this test kit at https://inferno.healthit.gov/ or running it locally? And if locally, did you set it up after April 23? 
We're in the process of migrating all our test kits from the Inferno validator wrapper to the HL7 validator wrapper; this one just migrated a week ago but we haven't updated the hosted version yet. Either way though, the validator should already be configured to allow any extensions so knowing which one you're using would help in confirming/debugging.

**Comment by gotdan** [comment]
Thanks! I tested using an older version of inferno running locally on my machine - I'll retest my server with the latest version and see if I still get errors.

**Comment by gotdan** [comment]
Confirmed that I'm not getting errors on extensions in the latest version!
