### ISSUE TITLE
Bulk Export V1 using smart app launch V2

### ISSUE THREAD

**Issue by nathanloyer** [inferno-framework/bulk-data-test-kit#23]
Hi there,

I was just attempting to run the bulk export v1.0.1 tests against a development server and noticed it was running tests specific to SMART App Launch V2. This server is conformant to the currently active g10 regulations, for which Smart V1 is the current requirement. It would be nice to be able to run the bulk export tests with Smart V1 instead. 

Specifically the server failed on the "grant_types_supported" requirement on the well-known smart configuration because that was an addition in Smart V2. We plan to support that before the deadline, but we have not implemented support for it yet.

**Comment by dehall** [comment]
Yeah that makes sense, thanks for pointing that out. We've added this to our list of items to address
